spring.application.name=api-gateway
server.port=8080

# JWT Config (same secret as Auth-Service)
jwt.secret=booknestSecretKeybooknestSecretKeybooknestSecretKey
jwt.expiration=3600000
jwt.prefix=Bearer
jwt.header=Authorization

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Gateway Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=catalog-service
spring.cloud.gateway.routes[1].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/books/**, /api/inventory/**

spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=lb://CART-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/cart/**

spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/orders/**, /addresses/**

spring.cloud.gateway.routes[4].id=wallet-service
spring.cloud.gateway.routes[4].uri=lb://WALLET-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/wallet/**

spring.cloud.gateway.routes[5].id=review-service
spring.cloud.gateway.routes[5].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/reviews/**

spring.cloud.gateway.routes[6].id=wishlist-service
spring.cloud.gateway.routes[6].uri=lb://WISHLIST-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/wishlist/**

spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/notifications/**



# Actuator / Health Probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Swagger UI Aggregation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=Catalog Service
springdoc.swagger-ui.urls[1].url=/books/v3/api-docs
springdoc.swagger-ui.urls[2].name=Cart Service
springdoc.swagger-ui.urls[2].url=/cart/v3/api-docs
springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/orders/v3/api-docs
springdoc.swagger-ui.urls[4].name=Wallet Service
springdoc.swagger-ui.urls[4].url=/wallet/v3/api-docs
springdoc.swagger-ui.urls[5].name=Notification Service
springdoc.swagger-ui.urls[5].url=/notifications/v3/api-docs
springdoc.swagger-ui.urls[6].name=Wishlist Service
springdoc.swagger-ui.urls[6].url=/wishlist/v3/api-docs
springdoc.swagger-ui.urls[7].name=Review Service
springdoc.swagger-ui.urls[7].url=/reviews/v3/api-docs

