# Server Config
server.port=8088
spring.application.name=wishlist-service

# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/booknest_wishlist?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=prateek@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Client Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator / Health Probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Swagger / OpenAPI
springdoc.api-docs.path=/wishlist/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/wishlist/swagger-ui.html

