# ===============================
# Server Configuration
# ===============================
server.port=8083
spring.application.name=cart-service

# ===============================
# Eureka Client Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/booknest_cart?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=prateek@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.booknest.cart=DEBUG

# Actuator / Health Probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Swagger / OpenAPI
springdoc.api-docs.path=/cart/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/cart/swagger-ui.html

